name: 04 - Using Actions

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: 04-using-actions/react-app
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: '22.x'
            - name: Install Dependencies
              run: |
                  npm config set legacy-peer-deps true
                  npm ci
            - name: Run Unit Tests
              run: npm run test
